### ISSUE TITLE
code loss

### ISSUE THREAD

**Issue by XiaoZiLijiqiao** [jinpeng01/HGN#1]
Traceback (most recent call last):
  File "E:\NLP_coding\HGN\HGN-main\run_hgn.py", line 1162, in <module>
    main()
  File "E:\NLP_coding\HGN\HGN-main\run_hgn.py", line 988, in main
    model = Ner.from_pretrained(args.output_dir)
NameError: name 'Ner' is not defined

**Comment by jinpeng01** [comment]
Thanks for your question.
you can try -do_predict to avoid this error
